-- require('telescope').load_extension('fzf')
-- require('telescope').setup{
--     defaults = {
--         -- winblend = 10, -- transparency
--         scroll_strategy = "limit",
--         vimgrep_arguments = {
--             "rg",
--             "--color=never",
--             "--no-heading",
--             "--with-filename",
--             "--line-number",
--             "--column",
--             "--smart-case",
--             "--trim" -- Removes indentation from results
--         }
--     },
--     pickers = {
--         find_files = {
--             find_command = { "fd", "--type", "f", "--strip-cwd-prefix" }
--         }
--     },
--     extensions = {
--         fzf = {
--             fuzzy = true,                    -- false will only do exact matching
--             override_generic_sorter = true,  -- override the generic sorter
--             override_file_sorter = true,     -- override the file sorter
--             case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
--             -- the default case_mode is "smart_case"
--         }
--     }
-- }
--
-- local opts = { noremap=true, silent=true }
-- local builtin = require('telescope.builtin')
--
-- vim.keymap.set("n", "<leader>f", "<cmd> Telescope find_files<CR>", opts)
-- vim.keymap.set("n", "<leader>g", "<cmd> Telescope live_grep<CR>", opts)
-- vim.keymap.set("n", "<leader>b", "<cmd> Telescope buffers<CR>", opts)
-- vim.keymap.set("n", "<leader>H", "<cmd> Telescope help_tags<CR>", opts)
-- vim.keymap.set('n', '<leader>O', builtin.oldfiles, opts)
